version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    working_directory: /root/project/ERGO.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.7
    steps:
      - run:
          command: julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.add(url="https://github.com/bencardoen/Colocalization.jl.git"), Pkg.add(url="https://github.com/bencardoen/ERGO.jl.git"); using Coverage; Pkg.test("ERGO", coverage=true);'
      - run:
          command: julia -e 'using Pkg; cd(Pkg.dir("ERGO")); using Coverage; Codecov.submit(Codecov.process_folder())'
