version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    working_directory: /root/project/ERGO.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.7
    steps:
      - checkout
      - run:
          name: Install and Test this package
          command: julia -e 'using Pkg; Pkg.update(); Pkg.activate("."); Pkg.build("ERGO"); Pkg.add("Coverage"), Pkg.test("ERGO", coverage=true); using Coverage; Codecov.submit(Codecov.process_folder())';'
