version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    working_directory: /root/project/ERGO.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.7
    steps:
      - run:
          name: Install and Test this package
          docker:
      - image: julia:1.7
    steps:
      - run:
          command: julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.add(url="https://github.com/bencardoen/ERGO.jl.git"); Pkg.test("ERGO", coverage=true); using Coverage; Codecov.submit(Codecov.process_folder());'
         
